---
output:
  html_document:
    theme: cosmo
---

## SISBID: Module 6 Gene Expression Analysis

**Instructors:** [Greg Gibson](http://cig.gatech.edu/) and [Jeff Leek](http://www.jtleek.com/)


**Class Schedule:**

* [Daily schedule](http://www.biostat.washington.edu/suminst/sisbid/schedule)
* [Location](http://www.biostat.washington.edu/suminst/sisbid/maps)


**Ressources:**


* [Rstudio](http://www.rstudio.com/), [R project](http://www.r-project.org/), and [Bioconductor](http://bioconductor.org/)
* [Rstudio's cheatsheets](http://www.rstudio.com/resources/cheatsheets/) & [Data.table cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/img/blog/data+table+cheat+sheet.pdf)
* [PH525x Book](http://genomicsclass.github.io/book/)

**Schedule**


| Day  | Date  |  Session | Resources  |  Description |
|---|---|---|---|---|
| 0  | 2015-07-08  | Background  | [Try R](http://tryr.codeschool.com/)  | Really simple intro to R online  |
| 0  | 2015-07-08  | Background | [swirl](http://swirlstats.com/)  | More tutorials on R, in R  |
|1 | 2015-07-08 | 1:30PM - 3:00PM | | Experimental Design |
|1 | --- | 3:00PM - 3:30PM | Break | --- |
|1 | 2015-07-08 | 3:30PM - 5:00PM | | Hypothesis testing |
|---|---|---|---|---|
|2 | 2015-07-09 | 8:30AM - 10:00AM | [html slides](https://slides.com/jeffleek/sisg-m6-d2) [pdf](https://dl.dropbox.com/s/38lqdzetv6bggmq/sisg-m6-d2.pdf)| Statistical foundations |
|2 | --- | 10:00AM - 10:30AM | Break | --- |
|2 | 2015-07-09 | 10:30AM - 12:00PM | | Normalization |
|2 | 2015-07-09 | 1:30PM - 3:00PM | |  Lab session – qvalue, PCA|
|2 | 2015-07-09 | 3:00PM - 3:30PM | Break | Break |
|2 | --- | 3:30PM - 5:00PM | | Lab session – SNM, edgeR|
|---|---|---|---|---|
|3 | 2015-07-09 | 8:30AM - 10:00AM | | RNASeq |
|3 | --- | 10:00AM - 10:30AM | Break | --- |
|3 | 2015-07-09 | 10:30AM - 12:00PM | | RNASeq |
|3 | 2015-07-09 | 1:30PM - 3:00PM | |  Advanced topics|
|3 | 2015-07-09 | 3:00PM - 3:30PM | Break | Break |
|3 | --- | 3:30PM - 5:00PM | | eQTL|


<!-- Add links to the rest of the material as we go



-->

**Miscellaneous**

Feel free to submit typos/errors/etc via the github repository associated with the class: 
https://github.com/jtleek/sisg

This web-page is modified from Andrew Jaffe's [Summer 2015 R course](http://www.aejaffe.com/summerR_2015/), which also has great material if you want to learn R. 

```{r, eval = FALSE, echo = FALSE}
## Render this file:
rmarkdown::render('index.Rmd')
```

This page was last updated on `r Sys.time()` Eastern Time.
